version: "3"
services:
  plantuml:
    container_name: ${COMPOSE_PROJECT_NAME}-planuml
    image: plantuml/plantuml-server:latest
    environment:
      # https://plantuml.com/ja-dark/faq
      - PLANTUML_LIMIT_SIZE=8192
    restart: always
    ports:
      - ${PLANTUML_PORT}:8080
